title: Joshua Cook
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Professional
  <br><br>
  Software Engineer
  <br><br>
  Educator
  <br><br>
  <br><a href="https://github.com/joshuacook">View My GitHub Profile</a> 
  <br><a href="https://www.linkedin.com/in/joshuapaulcook/">View My LinkedIn Profile</a> 
  <br><a href="https://stackexchange.com/users/1086120/joshua-cook">View My Stack Exchange Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-57847669-1 # your Google Analytics tracking ID here
